legal-name = "Stanley Renner"
current-title = "Software Engineer"

[location]
city = "East Carmeloside"
country = "Sweden"

[contact]
mail = "stanleyr@gmail.com"
telephone = "(+44) 7728533968"
social = ["https://www.github.com/myawesomeprofile", "https://www.linkedin.com/in/myawesomeprofile"]

[[work]]
name = "Cronin Group Ltd"
url = "https://www.cronin-group.com/"
location = ["Remote", "Stockholm"]
start-date = "Jan 2023"
end-date = "Present"
role = "Senior Software Engineer"
highlights = [
    "Sonitus tondeo blandior annus tenax ascit cerno vacuus triduana. Sol atrox desidero cupio ab adamo.",
    "Fuga tripudio tersus vulgaris. Vapulus cometes officia condico fuga subseco quo. Temporibus iste pauci voluptatum appositus solus recusandae vito apud trado. Varius ulterius in angustus vehemens.",
    "Umerus concedo cubitum incidunt. Tutamen avaritia aegrotatio anser commemoro tamisium debitis. Eligendi caste temporibus. Tam celer itaque attollo succedo apto desipio. Annus cuppedia creo artificiose aedificium coruscus claudeo dedico atqui. Truculenter vetus laboriosam ater bos conor temperantia vulgus.",
    "Tutamen assumenda quisquam caries vorax tot. Ante centum sperno sint cauda ventito appositus amissio cenaculum. Summa apud color traho calcar voveo dolores tempora. Voluntarius tergo carbo stultus comprehendo comis minus.",
]

[[work]]
name = "Kulas, Ward and Schuster Group Ltd"
url = "https://www.kws-group.com/"
location = ["Remote", "London"]
start-date = "May 2022"
end-date = "Jan 2023"
role = "Software Engineer"
highlights = [
    "Aliquid summopere vitium compono. Communis dapifer sumptus sed auditor villa thymum repellendus. Dolore venia nesciunt architecto subnecto sto. Terebro coma ducimus balbus cometes sumptus fugit explicabo coaegresco decet.",
    "Turbo theologus anser tamquam. Sint quas coniecto. Absque armarium cohaero decimus celer. Carpo pectus cupiditas curia termes. Viriliter asporto amiculum sophismata amet perspiciatis defaeco tres.",
    "Arbitro cum adduco fuga quis facilis triduana.",
    "Deprecator delego aliquam addo avarus umquam. Voro claustrum pariatur tempore mollitia deprecator sopor. Conscendo dens temeritas vomer desparatus. Demulceo sophismata tondeo credo amplexus amplexus.",
]

[[work]]
name = "Fisher and Sons Ltd"
url = "https://www.fisher-and-sons.com/"
location = ["Gotenberg"]
start-date = "Sep 2020"
end-date = "May 2022"
role = "Associate Software Engineer"
highlights = [
    "Clementia textor amiculum adsidue chirographum. Et esse totus valens ademptio calco.",
    "Delicate viriliter temperantia ver. Utroque cultellus caelestis absorbeo ter valetudo vilis degero aliqua ventito. Textor deorsum canonicus totus cuppedia ea argumentum repudiandae impedit pel.",
]

[education]
institution = "The University of Shields"
url = "https://www.shields-university.ac.uk/"
area = "Computer Science"
study-type = "Master of Science"
start-date = "Sep 2015"
end-date = "Jul 2019"
location.city = "Celestinoboro"
location.country = "Georgia"

[education.highlights]
honors = "MSc (Hons) Computer Science (First class)"
thesis = "Effiecient partnerships morph cross-cutting e-businesses at scale with dynamic systems (First class)"
courses = ["Advanced Algorithms", "Internet of Things", "Embedded Systems Programming", "Distributed and Enterprise Software Development"]
awards = ["Winner of the Division A debating Contest", "Finalist in the 2019 Stockholm Business evaluation project competition"]

[reference]
name = "Sherman Bode"
company = "Fisher and Sons"
role = "Senior Software Architect"
description = "Contact details on request"
